phase_info = {
    "pre_mission": {"include_takeoff": False, "optimize_mass": True},
    "climb_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": True,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 2,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.4, "unitless"),
            "final_mach": (0.82, "unitless"),
            "mach_bounds": ((0.27999999999999997, 0.84), "unitless"),
            "initial_altitude": (0.0, "ft"),
            "final_altitude": (35000, "ft"),
            "altitude_bounds": ((0.0, 35000), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": True,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((0.0, 0.0), "min"),
            "duration_bounds": ((0,200), "min"),
        },
        "initial_guesses": {"time": ([0, 200], "min")},
    },
    "cruise_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": True,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 2,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.82, "unitless"),
            "final_mach": (0.82, "unitless"),
            "mach_bounds": ((0.7999999999999999, 0.84), "unitless"),
            "initial_altitude": (35000, "ft"),
            "final_altitude": (35000, "ft"),
            "altitude_bounds": ((34500, 35500), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((0, 0), "min"),
            "duration_bounds": ((0, 1000), "min"),
        },
        "initial_guesses": {"time": ([0,1000], "min")},
    },
    "descent_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach":True,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 2,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.82, "unitless"),
            "final_mach": (0.4, "unitless"),
            "mach_bounds": ((0.27999999999999997, 0.84), "unitless"),
            "initial_altitude": (35000, "ft"),
            "final_altitude": (1000.0, "ft"),
            "altitude_bounds": ((500.0, 35000.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": False,
            "constrain_final": True,
            "fix_duration": False,
            "initial_bounds": ((0, 0), "min"),
            "duration_bounds": ((0, 200), "min"),
        },
        "initial_guesses": {"time": ([0, 200], "min")},
    },
    "post_mission": {
        "include_landing": False,
        "constrain_range": True,
        "target_range": (2690, "nmi"),
    },
}
